# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: depoly in aliyun

on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
  
    steps:
      - name: master
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build with Maven
        run: mvn package
        
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.ALIYUNIP }}' 
          ssh_private_key: '${{ secrets.ALIYUNSSHKEY }}' 
          local_path: './distribution/*'  # 对应我们项目build的文件夹路径
          remote_path: '/~/apps/lanproxy/'
          
